# Generated by Django 4.2.6 on 2023-10-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(default='path/to/default_qr_code.png', upload_to='qrcodes/'),
        ),
    ]
